# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Wavelog
version: "2.0.1"
slug: wavelog
description: Wavelog Ham Radio logbook
map:
  - type: addon_config
    read_only: false
    path: /var/www/html/application/config/docker
arch:
  - amd64
init: false
environment:
  CI_ENV: docker
startup: services
ports:
  80/tcp: 8086
options:
  access_log: False
schema:
  access_log: bool
